### ISSUE TITLE
nothing shows on meta box

### ISSUE THREAD

**Issue by amitrahav** [Mte90/CMB2-User-Search-field#3]
hey, i can see every element has style attr with display:none;
what should trigger the appearance? 
i get no js errors on console - every thing seems to be loading fine.

**Comment by Mte90** [comment]
what is the problem? I hide the input text and show the button that open the internal window so i don't understand the problem

**Comment by amitrahav** [comment]
![image](https://cloud.githubusercontent.com/assets/1517479/17462784/6f2c5cd0-5cc0-11e6-90fb-91570de218fb.png)
theres nothing under this metabox...

**Comment by Mte90** [comment]
This metabox are cmb metabox?I can see the code? You tried with other fields?

**Comment by amitrahav** [comment]
```
add_action( 'cmb2_init', 'cmb2_add_users' );
function cmb2_add_users() {
    require_once get_template_directory() . '/CMB2/cmb2-user-search-field/cmb2_user_search_field.php';
    $prefix = '_startup_';

    $user_meta = new_cmb2_box( array(
        'id'           => $prefix . 'userstitle',
        'title'        => __( 'Attached Users', 'cmb2' ),
        'object_types' => array( 'startup' ), // Post type
        'context'      => 'normal',
        'priority'     => 'high',
        'show_names'   => false, // Show field names on the left
    ) );

    $user_meta->add_field( array(
        'name'    => __( 'Attached Users', 'cmb2' ),
        'id'      => $prefix . 'users',
        'type'    => 'user_search_text',
        'roles' => array( 'administrator', 'author', 'editor' )
    ) );

}
```

**Comment by Mte90** [comment]
The problem is the include of the field, use inside an hook that it is already invoked in cmb2_init, you have to move that include outside that hook.

**Comment by amitrahav** [comment]
where should i include it?

`
require_once get_template_directory() . '/CMB2/cmb2-user-search-field/cmb2_user_search_field.php';
add_action( 'cmb2_init', 'cmb2_add_users' );
function cmb2_add_users() {
...
}    
`

some thing like this?

**Comment by Mte90** [comment]
yes

**Comment by amitrahav** [comment]
Don't work that way...

**Comment by Mte90** [comment]
Very strange i use without problems in many plugins, you tried to replace the type with another one?
for me there is a problem during the loading the user field

**Comment by amitrahav** [comment]
everything loads fine, it's just dispaly:none;
![image](https://cloud.githubusercontent.com/assets/1517479/17517263/488bfd6a-5e4b-11e6-990f-e27bb27357b0.png)

what should be displayed? or what should trigger the display?

**Comment by Mte90** [comment]
okay the field it's loaded but it's missing the javascript execution, can you paste here what error you get on the console?

**Comment by amitrahav** [comment]
actually js loaded after the input...
![image](https://cloud.githubusercontent.com/assets/1517479/17517925/4eef7cd8-5e4e-11e6-8595-00ac59488c72.png)

there's no error on consple

**Comment by Mte90** [comment]
well theis are the inspector not the js console.

**Comment by amitrahav** [comment]
if there where errors it would show a number next to the console tab
![image](https://cloud.githubusercontent.com/assets/1517479/17518129/3ec0069c-5e4f-11e6-839d-cc38d2b559aa.png)

**Comment by Mte90** [comment]
very strange I have no idea what is happening

**Comment by amitrahav** [comment]
when i remove the display:none; it's working.
what should trigger it?
and the opening of the popup?

**Comment by Mte90** [comment]
as you can see in the readme https://github.com/Mte90/CMB2-User-Search-field/blob/master/README.md this is what require to be showed.

**Comment by amitrahav** [comment]
nothing on this subject is mention on readme file.

**Comment by amitrahav** [comment]
![image](https://cloud.githubusercontent.com/assets/1517479/17520392/417abd9c-5e58-11e6-8304-dd54f9adc140.png)
works when i remove display none menualy...

**Comment by amitrahav** [comment]
got it!
youre using .cmb-td as selector in all js functions - to add search button, to bind it to open popup function...
I dont know why, but cmb2 dosent use it in my version (leatest).
once i removed it - every thing works fine.

any idea if .cmb-td is essential for something else?

**Comment by Mte90** [comment]
Maybe the cmb selector are changed in the last update, i am not sure to using the last version but I will check asap!
Thanks for the fix!

**Comment by Mte90** [comment]
I am using the last version of cmb and this problem not happen, can you give me the version of cmb that you are using?
